### ISSUE TITLE
Unable to use make commands

### ISSUE THREAD

**Issue by burdenyuk** [contentful/ui-extensions-sdk#130]
Hello guys!

I was trying today to install ui-extension alloyeditor and had problems: editor could not be rendered when I was going to localhost:3000, however it's not the main problem, perhaps you could lead me to the what is wrong here.

And main problem: I saw you added changes related to renaming widgets to extension and now I am not able to run make commands.

Steps I did:

I cloned the repo https://github.com/contentful/extensions, navigated to folder samples/alloy-editor (https://github.com/contentful/extensions/tree/master/samples/alloy-editor) and did steps from README. The problem appears when I invoke make commands:

```
make create
contentful-extension create --space-id xxx
Failed to create the extension: TypeError: Cannot read property 'id' of undefined
make: *** [create] Error 1
```

p.s: links to ui-extensions are messed up on this page - https://www.contentful.com/developers/docs/concepts/uiextensions/

**Comment by hlabas** [comment]
Hi Denis,
We're currently releasing the changes which is why you're currently experiencing the error. This repository has been made public earlier to allow us to test these changes and we're about to publish the documentation changes.
We will update this thread once the release is completed so you can verify if everything works as expected.
Thank you for your understanding,
Hervé

**Comment by hlabas** [comment]
The release is complete and the issue you were facing should be resolved.
Let us know if you encounter any problem going further.
Thank you!
Hervé
