### ISSUE TITLE
extensions.locales.available should return labels as well

### ISSUE THREAD

**Issue by vkhare** [contentful/ui-extensions-sdk#180]
extensions.locales.available only returns an array of the locale codes. It would be nice to get the locale names as well e.g. German(Germany)

**Comment by jelz** [comment]
Hi there, we've just released a new version of the SDK including locale names.

We couldn't change the format of `extension.locales.available` since it would be a breaking change but we expose them as an object under `extension.locales.names`. The whole `extension.locales` namespace looks like this now: 

```js
{
  available: ['en-US', 'pl'],
  default: 'en-US',
  names: {
    'en-US': 'English (US)',
    pl: 'Polski'
  }
}
```

Hope it helps.
